version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - back

  db:
    image: mysql:5.7
    volumes:
       - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cakephp_db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    ports:
      - 3306:3306 
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    hostname: db.local
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      back:
        aliases:
          - db.local

networks:
  back:
    driver: bridge
volumes:
  db_data: